// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gixbqoyczdactpwdvcqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpeGJxb3ljemRhY3Rwd2R2Y3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDQ5MjAsImV4cCI6MjA3MzE4MDkyMH0.FOUm6dGC_Oe91bnT1P44lPgqCld2v0Ax9T9nUosdG28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});